### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by c-goosen** [Doist/bitmapist-server#1]
Hi.

Interesting project we are looking at to implement in a new project. Still in its infancy it seems, but we are starting to look at things we had with redis like clustering. Considered having a 24hr file and then main file for persistence? This allows a fail-over scenario that you can recover by copying main file to new cluster node and systematically send the chunks in the 24hour file to the new node. 

I am very keen to write some code and test clustering scenarios. Currently our work around is using a streaming service like kafka or Kinesis (AWS) to stream to 2 nodes. One node for active usage and another for hot-standby. So the streaming would be consumed by a client on the same node and written to bitmapist-server via python client lib. 

Thanks
Christo Goosen

**Comment by artyom** [comment]
Christo, thank you for the feedback!

The goal of this project was to address specific issue we had using redis bitmaps — high memory consumption. So the main direction of optimizations was reducing memory footprint. Currently this is achieved mainly by two tricks: 1) using compressed bitmaps, 2) keeping only hot data in memory. These factors do not play well with log-alike persistence scheme, though I can imagine such implementation if another storage backend is used, something like LevelDB.

As for clustering and hot-standby scenarios this can probably be addressed by proxy layer that can fan-out write requests to multiple nodes and route read requests to a single node. This is the direction I'd go with implementation if faced with online replication / hot-standby use case, so your current workaround is almost the same thing but using a combination of streaming service + client as a middle-man. Built-in clustering support was explicitly avoided initially in favor of design simplicity and performance.

I will currently mark this as wontfix as it's not an issue in use case it was originally designed for — though I may come back to this later, but please feel free to re-open this is if you have any code to merge or discuss some implementation details.
