### ISSUE TITLE
Can we use Docker Hub for Docker packages?

### ISSUE THREAD

**Issue by imankulov** [Doist/bitmapist-server#15]
I wanted to document the usage of bitmapist-server from Docker and found out that it's challenging.

As it turns out, [github package registry](https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32782) is quite useless for public builds ("docker pull" doesn't work).

Likely, GitHub fixes this issue soon (they promised in the thread), and we can simply put it on hold until then, or we can migrate to Docker Hub.

**Comment by artyom** [comment]
Let's wait with this for now as you suggested. It looks that the only challenging thing about Github-hosted docker registry is that you [first need to authenticate](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-docker-for-use-with-github-packages).

You can create a token at <https://github.com/settings/tokens>, it needs `read:packages`, `repo` scopes. Then use it to log into the registry:

    $ docker login -u USERNAME -p TOKEN docker.pkg.github.com

After this step commands from [package details page](https://github.com/Doist/bitmapist-server/packages/70714) work. The steps to log in are described in an article that's linked on the same page, so I don't see this as a major inconvenience.

If this proves to be a major stumbling point, we can reconsider this and publish to docker hub directly.
