### ISSUE TITLE
Vendor directory

### ISSUE THREAD

**Issue by c-goosen** [Doist/bitmapist-server#2]
Hi

Is the vendor directory for version pinning? Can we not use something like Go Package Manager and a file with all the dependencies? 

Thanks
Christo

**Comment by artyom** [comment]
Yes, [vendor directory is for version pinning](https://golang.org/cmd/go/#hdr-Vendor_Directories) and ensuring that project stays go-gettable and not breaks if some dependency package API changes. You don't have to use any package manager to build this project, it's only used as a convenience when collecting/updating vendored dependencies, the binary itself can be built as described in README with this command:

    go get -u github.com/Doist/bitmapist-server
