### ISSUE TITLE
Data exists but inaccessable

### ISSUE THREAD

**Issue by altunyurt** [Doist/bitmapist-server#3]
I've been using bitmapist for storing user activity for quite some time. But apparently some data despite still being in the database is not accessible anymore since a couple days ago. I'm backing up the data periodicallyevery day and also checking out the data representation over the web app, but now data regarding last 3 months, since may 3rd to be precise,  is not accessible anymore. 

I've also checked the daily backups back to july and i can't access the data there either even though i could read the data over the app and did not have any problems those days.  

This is how i check the backups: 
```
➜  ~ ~/.golang/bin/bitmapist-server -addr localhost:6380 -debug -db 2018_07_29_bitmapist.db 
2018/08/26 20:50:40 loading data from 2018_07_29_bitmapist.db
2018/08/26 20:50:40 loaded in 4.656269ms
2018/08/26 20:50:45 conn:1	[COMMAND]
2018/08/26 20:50:47 conn:1	[keys trackist_user:join_2018-5*]
2018/08/26 20:53:40 periodic saving...
2018/08/26 20:53:40 saved in 36ms
2018/08/26 20:56:40 periodic saving...
2018/08/26 20:56:40 saved in 30ms

....

➜  ~ redis-cli -p 6380                                    
127.0.0.1:6380> keys trackist_user:join_2018-5*
1) "trackist_user:join_2018-5-2"
2) "trackist_user:join_2018-5-1"
3) "trackist_user:join_2018-5"
4) "trackist_user:join_2018-5-3"
127.0.0.1:6380> 
```

Go: v1.10
Bitmapist server: 1.0.1 and latest 

I know the data exists in the db and backups, since i was able to read it online but is there any other way to access the data to confirm ?

**Comment by altunyurt** [comment]
Just moved my system to another infrastructure and fired up bitmapist-server with the dump taken from the former instance triggered with sigusr1. 
The dump file is 180M and it contains all the keys in. I can see the keys, i can query the keys but the bitcount returns 0 for all. Exactly the same problem: data is there but i can not reach it.  

I've compiled bitmapist-server commit 8b25fa79d093207f2102c735703984d3cdedcf7c with go-1.11.

**Comment by artyom** [comment]
@altunyurt can you please try version tagged as v1.4.1 (most recent one)?

**Comment by altunyurt** [comment]
thank you @artyom. It seems to be working. I still have some data missing though, but most is accessible now.
