### ISSUE TITLE
How stable is it?

### ISSUE THREAD

**Issue by mherrmann** [Doist/bitmapist-server#6]
Hi,

I'm thinking of using bitmapist-server but am unsure how stable it is. Are you using it in production? With how much data? Can you recommend using it for live data, or would you say it's still too early?

Thanks,
Michael

**Comment by artyom** [comment]
@mherrmann we use it in production for over a year now, it replaced previously used redis instance that required over 120 Gb of memory to hold all data.

I suggest you test it on a workload you expect to see in production (number of keys, hot/cold keys ratio, request rate) and see whether it works fine.

**Comment by mherrmann** [comment]
Okay. Thanks!
